apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "squid.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "squid.labels" . | nindent 4 }}
data:
  squid.conf: |-
    {{- .Files.Get "squid.conf" | nindent 4 }}

    {{- if .Values.tlsOutgoingOptions.caFile }}
    tls_outgoing_options cafile={{ .Values.tlsOutgoingOptions.caFile }}
    {{- end }}

    {{- if .Values.cache.allowList }}
    {{- range .Values.cache.allowList }}
    acl cached_urls url_regex {{ . }}
    {{- end }}

    cache allow cached_urls
    cache deny all
    {{- else }}
    cache allow all
    {{- end }}

    # --- MEMORY CACHE CONFIGURATION ---
    cache_mem {{ .Values.cache.memory.size }}
    maximum_object_size_in_memory {{ .Values.cache.memory.maxObjectSize }}
