apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "squid.fullname" . }}-ssl-db
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "squid.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sslDb.storage.size | default "1Gi" }}
  {{- if .Values.sslDb.storage.storageClass }}
  storageClassName: {{ .Values.sslDb.storage.storageClass }}
  {{- end }} 
